#!/bin/bash

# TO-DO APP - SETUP AND RUN SCRIPT

echo "🚀 To-Do App Launcher"
echo "===================="
echo ""
echo "PREREQUISITES CHECK:"
echo "✓ MySQL running?"
echo "✓ npm installed?"
echo ""

echo "STEP 1: Install Dependencies"
echo "----------------------------"
echo "Run: npm install"
echo ""

echo "STEP 2: Create MySQL Database"
echo "-----------------------------"
echo "Run in MySQL:"
echo "  CREATE DATABASE todo_app;"
echo ""

echo "STEP 3: Start Backend Server (Terminal 1)"
echo "-----------------------------------------"
echo "Run: npm run server"
echo "Expected: 'Server running on http://localhost:5000'"
echo ""

echo "STEP 4: Start Frontend (Terminal 2)"
echo "-----------------------------------"
echo "Run: npm run dev"
echo "Expected: 'Local: http://localhost:5173'"
echo ""

echo "STEP 5: Open Browser"
echo "-------------------"
echo "Go to: http://localhost:5173"
echo ""

echo "✨ NOW CREATE YOUR FIRST TODO!"
echo "==============================="
echo "1. Type todo title"
echo "2. Add description (optional)"
echo "3. Pick due date (optional)"
echo "4. Click 'Add Task'"
echo "5. Your todo appears below!"
echo ""

echo "📝 TODO MANAGEMENT"
echo "=================="
echo "✓ Create  - Click 'Add Task' button"
echo "✓ Read    - See all todos in list"
echo "✓ Update  - Click 'Edit' button"
echo "✓ Delete  - Click 'Delete' button"
echo "✓ Toggle  - Click checkbox to mark complete"
echo ""

echo "📁 FILES CREATED"
echo "================"
echo "Frontend:"
echo "  • src/TodoForm.jsx   - New todo input form"
echo "  • src/TodoList.jsx   - Todo list container"
echo "  • src/TodoItem.jsx   - Individual todo item"
echo "  • src/App.jsx        - UPDATED: Main app logic"
echo ""
echo "Backend:"
echo "  • server.js          - Express API server"
echo ""
echo "Documentation:"
echo "  • SETUP.md           - Detailed setup guide"
echo "  • QUICK_START.md     - Quick reference"
echo "  • MYSQL_CONFIG.md    - Database config options"
echo "  • BUILD_COMPLETE.md  - Full overview"
echo ""

echo "🆘 TROUBLESHOOTING"
echo "=================="
echo "Can't connect to MySQL?"
echo "  → Check MySQL is running"
echo "  → Update credentials in server.js"
echo "  → See MYSQL_CONFIG.md for options"
echo ""
echo "API errors in console?"
echo "  → Make sure npm run server is running"
echo "  → Check server port is 5000"
echo ""
echo "Need help?"
echo "  → Read SETUP.md for detailed instructions"
echo "  → Check MYSQL_CONFIG.md for database setup"
echo ""

echo "🎉 READY TO GO!"
echo "==============="
echo "Follow the steps above and start managing your tasks!"
